language: java
jdk:
  - oraclejdk8
notification:
  email:
    recipients:
      - seimimaster@gmail.com
    on_success: always
    on_failure: always

after_success:
  - mvn clean compile test

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.m2